# [flavor]
# dark  = "dracula"
# light = ""

[filetype]

rules = [
  { name = "*.config/", fg = "#eeeeee", bold = true },           # make .config stand out
  { name = "*.local/", fg = "#eeeeee", bold = true },            # make .config stand out
  { name = "*.cache/", fg = "#eeeeee", bold = true },            # make .config stand out
  { mime = "inode/directory", is = "hidden", fg = "brightred" }, # hide hidden folders

   # Images
   { mime = "image/*", fg = "cyan" },

   # Media
   { mime = "video/*", fg = "magenta" },
   { mime = "audio/*", fg = "yellow" },

   # Archives
   { mime = "application/zip", fg = "red" },
   { mime = "application/x-tar", fg = "red" },
   { mime = "application/x-bzip*", fg = "red" },
   { mime = "application/x-bzip2", fg = "red" },
   { mime = "application/x-7z-compressed", fg = "red" },
   { mime = "application/x-rar", fg = "red" },
   { mime = "application/x-xz", fg = "red" },

   # Documents
   { mime = "application/doc", fg = "green" },
   { mime = "application/epub+zip", fg = "green" },
   { mime = "application/pdf", fg = "green" },
   { mime = "application/rtf", fg = "green" },
   { mime = "application/vnd.*", fg = "green" },

   { name = "*", fg = "blue" },
   { name = "*/", fg = "brightgreen" },
]
